apps:
  - name: helloworld1
    script: index.js
    cwd: /var/www/helloworld1/
    watch: true
    exec_mode: cluster
    env:
      NODE_PORT: 8081

  - name: helloworld2
    script: index.js
    cwd: /var/www/helloworld2/
    watch: true
    exec_mode: cluster
    env:
      NODE_PORT: 8082